# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
  - stage: Dev
    jobs:
    - job: job1
      steps:
        - script: echo Hello world
          displayName: Running first job
    - job: job2
      dependsOn: job1
      steps:
        - bash: echo This is job2
          displayName: Running job2

  - stage: Prod
    jobs:
    - job: job3
      steps:
        - script: echo Hello world
          displayName: Running first job
    - job: job4
      dependsOn: job3
      steps:
        - bash: echo This is job2
          displayName: Running job2


  - stage: QA
    jobs:
    - job: job5
      steps:
        - script: echo Hello world
          displayName: Running first job
    - job: job2
      dependsOn: Prod
      steps:
        - bash: echo This is job2
          displayName: Running job2
