
trigger:
- master

pool:
  VmImage: 'ubuntu-latest'
stages:
  - stage: Dev
    jobs:
      - deployment: DEV-deploy_joob
        environment: dev
        strategy: 
         runOnce:
           deploy:
             steps:
               - script: eccho deploy to dev
         