
trigger:
- master

strategy: 
  matrix:
    linux:
      os: 'ubuntu-latest'
    mac:
      os: 'macos-latest'

     
pool:
  VmImage: $(os)

stages:
  - stage: Publishing_Artifacts_files
    jobs:
      - job: copying_artifacts_files
        steps:
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)'
              ArtifactName: 'Master_Branch_files'
              publishLocation: 'Container'