
trigger:
- master

pool:
  VmImage: 'ubuntu-latest'
stages:
  - stage: Dev
    jobs:
      - job: Build_and_push_docker_images
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker_Registry'
              repository: 'bijuthomaspta/currency-exchange-microservice-basic-2024'
              command: 'build'
              Dockerfile: '$(System.DefaultWorkingDirectory)/projects/microservices/01-currency-exchange-microservice-basic/Dockerfile'

          - task: Docker@2
            inputs:
              containerRegistry: 'Docker_Registry'
              repository: 'bijuthomaspta/currency-exchange-microservice-basic-2024'
              command: 'push'
              tags: '07.01.2024'