
trigger:
- master
pool:
  VmImage: 'Ubuntu-latest'

stages:
  - stage: Publishing_Artifacts files
    jobs:
      - job: copying_artifacts_files
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - bash: ls -R '$(Build.ArtifactStagingDirectory)'
      - job: publishing_artifacts_files
        dependsOn: copying_artifacts_files
        condition: always()
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'Master_Branch_files'
              publishLocation: 'Container'